FILTER_WIDTH: 3
LIB_SUBSET_SIZE: 2
IMAGE_SIZE: 64
VIDEO_FILE: "Input_Video/Cone1_input_video.mp4"
OUTPUT_FILE: "output/Reconstructed Video"
TRUE_ANGLES: ""
SIGMA: 40
DATABASE_ZIP: "cone.zip"
NEW_LIB: true