FILTER_WIDTH: 0.001
LIB_SUBSET_SIZE: 2
IMAGE_SIZE: 128
VIDEO_FILE: "Input_Video/TridentII_D5_input_1_noise.mp4"
OUTPUT_FILE: "output/Reconstructed_Video_Missile"
TRUE_ANGLES: ""
SIGMA: 40
DATABASE_ZIP: "missile.zip"
NEW_LIB: false