FILTER_WIDTH: 3
LIB_SUBSET_SIZE: 2
IMAGE_SIZE: 64
VIDEO_FILE: "Input_Video/Dragon1_input_2deg.mp4"
OUTPUT_FILE: "output/Reconstructed Video"
TRUE_ANGLES: ""
SIGMA: 40
DATABASE_ZIP: "dragon.zip"
NEW_LIB: false